@startuml

title __NET's Class Diagram__\n

  namespace com.kedacom.vconf.sdk.utils {
    namespace net {
      class com.kedacom.vconf.sdk.utils.net.NetAddrHelper {
          {static} - IPV4_SPLITTER : Splitter
          {static} + ipInt2Str()
          {static} + ipStr2Int()
          {static} + isValidHost()
          {static} + isValidHost()
          {static} + isValidIp()
          {static} + isValidMask()
          {static} + isValidNetConfig()
          {static} + maskIp2Len()
          {static} + maskLen2Ip()
          {static} - isIpValidMask()
      }
    }
  }
  

  namespace com.kedacom.vconf.sdk.utils {
    namespace net {
      class com.kedacom.vconf.sdk.utils.net.NetAddrHelper.InvalidIpv4Exception {
          + InvalidIpv4Exception()
          + InvalidIpv4Exception()
      }
    }
  }
  

  namespace com.kedacom.vconf.sdk.utils {
    namespace net {
      class com.kedacom.vconf.sdk.utils.net.NetworkHelper {
          {static} + STATE_CONNECTED : int
          {static} + STATE_DISCONNECTED : int
          {static} + TRANS_CELLULAR : int
          {static} + TRANS_ETHERNET : int
          {static} + TRANS_UNKNOWN : int
          {static} + TRANS_VPN : int
          {static} + TRANS_WIFI : int
          {static} - connMan : ConnectivityManager
          {static} - netInfo : NetInfo
          {static} - wifiMan : WifiManager
          {static} + getAddr()
          {static} + getDns()
          {static} + getGateway()
          {static} + getMask()
          {static} + getTransType()
          {static} + init()
          {static} + isConnected()
          {static} - getDnsFromSystemProperties()
          {static} - getIpAddress()
          {static} - updateNetInfo()
          {static} - updateNetInfo()
          {static} - updateNetInfo()
          {static} - updateNetInfo()
      }
    }
  }
  

  namespace com.kedacom.vconf.sdk.utils {
    namespace net {
      class com.kedacom.vconf.sdk.utils.net.NetworkHelper.MyNetworkCallback {
          + onAvailable()
          + onLinkPropertiesChanged()
          + onLost()
      }
    }
  }
  

  namespace com.kedacom.vconf.sdk.utils {
    namespace net {
      class com.kedacom.vconf.sdk.utils.net.NetworkHelper.NetInfo {
          ~ addr : String
          ~ dns : String
          ~ gateway : String
          ~ mask : String
          ~ state : int
          ~ transType : int
          + toString()
          ~ clear()
      }
    }
  }
  

  com.kedacom.vconf.sdk.utils.net.NetAddrHelper +-down- com.kedacom.vconf.sdk.utils.net.NetAddrHelper.InvalidIpv4Exception
  com.kedacom.vconf.sdk.utils.net.NetworkHelper +-down- com.kedacom.vconf.sdk.utils.net.NetworkHelper.MyNetworkCallback
  com.kedacom.vconf.sdk.utils.net.NetworkHelper +-down- com.kedacom.vconf.sdk.utils.net.NetworkHelper.NetInfo
  com.kedacom.vconf.sdk.utils.net.NetworkHelper.MyNetworkCallback -up-|> android.net.ConnectivityManager.NetworkCallback


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
