


@startuml

title <size:24><b>数据协作基本流程\n\n

|接入模块|
start
:登录APS;

|#AntiqueWhite|数据协作模块|
:登录数据协作;
floating note left
目前，登录协作必须
在登录APS成功以后
end note

|会议模块|
:入会;
note right
目前数据协作
依附于会议，
只有在会议中
才能开数据协作
end note

|数据协作模块|
:开始数据协作;
floating note left
数据协作有两种模式：
自由协作和管理员审批，
前者则任何人都有协作权，
后者则需向管理员申请。
该模式由会议管理员设置。
end note


if (是否有协作权) then (否)

    :申请协作权;

    if (审批通过？) then (是)
        :接收/发送数据协作;
    else (否)
        :接收数据协作;
    endif

else (是)
    :接收/发送数据协作;
endif

    :退出/结束数据协作;

    :注销数据协作;
    stop

@enduml
