@startuml

title __BEAN's Class Diagram__\n

  namespace com.kedacom.vconf.sdk.main {
    namespace im {
      namespace bean {
        class com.kedacom.vconf.sdk.main.im.bean.TIMSvrAddr {
        }
      }
    }
  }
  

  namespace com.kedacom.vconf.sdk.main {
    namespace im {
      namespace bean {
        class com.kedacom.vconf.sdk.main.im.bean.TImLoginResult {
            + achReserved : String
            + dwErrID : int
            + dwHandle : long
            + dwReserved : int
        }
      }
    }
  }
  

  namespace com.kedacom.vconf.sdk.main {
    namespace im {
      namespace bean {
        class com.kedacom.vconf.sdk.main.im.bean.TImUserLogin {
            + achConfigPath : String
            + achDefaultSaveDir : String
            + achEnterpriseName : String
            + achNO : String
            + achPicSaveDir : String
            + achResource : String
            + achSock5Addr : String
            + achSock5Password : String
            + achSock5Username : String
            + achStunAddr : String
            + achUserPwd : String
            + bAudioCapability : boolean
            + bCompression : boolean
            + bFileShareEnable : boolean
            + bInstant : boolean
            + bUseSock5 : boolean
            + bVideoCapability : boolean
            + byPwdLen : short
            + dwImIP : long
            + wPort : int
            + wSock5Port : int
            + wStunPort : int
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
