// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.kedacom.mt.netmanage.protobuf;

public final class MessagePB {
  private MessagePB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TMsgHeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string msg_id = 1;
    /**
     * <code>optional string msg_id = 1;</code>
     *
     * <pre>
     *消息id，唯一标识一个消息
     * </pre>
     */
    boolean hasMsgId();
    /**
     * <code>optional string msg_id = 1;</code>
     *
     * <pre>
     *消息id，唯一标识一个消息
     * </pre>
     */
    String getMsgId();
    /**
     * <code>optional string msg_id = 1;</code>
     *
     * <pre>
     *消息id，唯一标识一个消息
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    // optional string session_id = 2;
    /**
     * <code>optional string session_id = 2;</code>
     *
     * <pre>
     *会话id，唯一标识一个会话源
     * </pre>
     */
    boolean hasSessionId();
    /**
     * <code>optional string session_id = 2;</code>
     *
     * <pre>
     *会话id，唯一标识一个会话源
     * </pre>
     */
    String getSessionId();
    /**
     * <code>optional string session_id = 2;</code>
     *
     * <pre>
     *会话id，唯一标识一个会话源
     * </pre>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    // optional uint32 seq_id = 3;
    /**
     * <code>optional uint32 seq_id = 3;</code>
     *
     * <pre>
     *序列号，唯一标识一次请求
     * </pre>
     */
    boolean hasSeqId();
    /**
     * <code>optional uint32 seq_id = 3;</code>
     *
     * <pre>
     *序列号，唯一标识一次请求
     * </pre>
     */
    int getSeqId();

    // optional string user_data = 4;
    /**
     * <code>optional string user_data = 4;</code>
     *
     * <pre>
     *特定场景使用，如fcgi请求可以使用该字段存放会话标识，用于返回响应
     * </pre>
     */
    boolean hasUserData();
    /**
     * <code>optional string user_data = 4;</code>
     *
     * <pre>
     *特定场景使用，如fcgi请求可以使用该字段存放会话标识，用于返回响应
     * </pre>
     */
    String getUserData();
    /**
     * <code>optional string user_data = 4;</code>
     *
     * <pre>
     *特定场景使用，如fcgi请求可以使用该字段存放会话标识，用于返回响应
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserDataBytes();

    // repeated string req_path = 5;
    /**
     * <code>repeated string req_path = 5;</code>
     *
     * <pre>
     *	optional string req_src_id = 5;  //req消息的初始发送者，仅用于req/rsp消息的接力处理
     * </pre>
     */
    java.util.List<String>
    getReqPathList();
    /**
     * <code>repeated string req_path = 5;</code>
     *
     * <pre>
     *	optional string req_src_id = 5;  //req消息的初始发送者，仅用于req/rsp消息的接力处理
     * </pre>
     */
    int getReqPathCount();
    /**
     * <code>repeated string req_path = 5;</code>
     *
     * <pre>
     *	optional string req_src_id = 5;  //req消息的初始发送者，仅用于req/rsp消息的接力处理
     * </pre>
     */
    String getReqPath(int index);
    /**
     * <code>repeated string req_path = 5;</code>
     *
     * <pre>
     *	optional string req_src_id = 5;  //req消息的初始发送者，仅用于req/rsp消息的接力处理
     * </pre>
     */
    com.google.protobuf.ByteString
        getReqPathBytes(int index);
  }
  /**
   * Protobuf type {@code mt.TMsgHeader}
   */
  public static final class TMsgHeader extends
      com.google.protobuf.GeneratedMessage
      implements TMsgHeaderOrBuilder {
    // Use TMsgHeader.newBuilder() to construct.
    private TMsgHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TMsgHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TMsgHeader defaultInstance;
    public static TMsgHeader getDefaultInstance() {
      return defaultInstance;
    }

    public TMsgHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TMsgHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              msgId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sessionId_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              seqId_ = input.readUInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              userData_ = input.readBytes();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                reqPath_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              reqPath_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          reqPath_ = new com.google.protobuf.UnmodifiableLazyStringList(reqPath_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessagePB.internal_static_mt_TMsgHeader_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessagePB.internal_static_mt_TMsgHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TMsgHeader.class, Builder.class);
    }

    public static com.google.protobuf.Parser<TMsgHeader> PARSER =
        new com.google.protobuf.AbstractParser<TMsgHeader>() {
      public TMsgHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TMsgHeader(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<TMsgHeader> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string msg_id = 1;
    public static final int MSG_ID_FIELD_NUMBER = 1;
    private Object msgId_;
    /**
     * <code>optional string msg_id = 1;</code>
     *
     * <pre>
     *消息id，唯一标识一个消息
     * </pre>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string msg_id = 1;</code>
     *
     * <pre>
     *消息id，唯一标识一个消息
     * </pre>
     */
    public String getMsgId() {
      Object ref = msgId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg_id = 1;</code>
     *
     * <pre>
     *消息id，唯一标识一个消息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      Object ref = msgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string session_id = 2;
    public static final int SESSION_ID_FIELD_NUMBER = 2;
    private Object sessionId_;
    /**
     * <code>optional string session_id = 2;</code>
     *
     * <pre>
     *会话id，唯一标识一个会话源
     * </pre>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string session_id = 2;</code>
     *
     * <pre>
     *会话id，唯一标识一个会话源
     * </pre>
     */
    public String getSessionId() {
      Object ref = sessionId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string session_id = 2;</code>
     *
     * <pre>
     *会话id，唯一标识一个会话源
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint32 seq_id = 3;
    public static final int SEQ_ID_FIELD_NUMBER = 3;
    private int seqId_;
    /**
     * <code>optional uint32 seq_id = 3;</code>
     *
     * <pre>
     *序列号，唯一标识一次请求
     * </pre>
     */
    public boolean hasSeqId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 seq_id = 3;</code>
     *
     * <pre>
     *序列号，唯一标识一次请求
     * </pre>
     */
    public int getSeqId() {
      return seqId_;
    }

    // optional string user_data = 4;
    public static final int USER_DATA_FIELD_NUMBER = 4;
    private Object userData_;
    /**
     * <code>optional string user_data = 4;</code>
     *
     * <pre>
     *特定场景使用，如fcgi请求可以使用该字段存放会话标识，用于返回响应
     * </pre>
     */
    public boolean hasUserData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string user_data = 4;</code>
     *
     * <pre>
     *特定场景使用，如fcgi请求可以使用该字段存放会话标识，用于返回响应
     * </pre>
     */
    public String getUserData() {
      Object ref = userData_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userData_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string user_data = 4;</code>
     *
     * <pre>
     *特定场景使用，如fcgi请求可以使用该字段存放会话标识，用于返回响应
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserDataBytes() {
      Object ref = userData_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string req_path = 5;
    public static final int REQ_PATH_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList reqPath_;
    /**
     * <code>repeated string req_path = 5;</code>
     *
     * <pre>
     *	optional string req_src_id = 5;  //req消息的初始发送者，仅用于req/rsp消息的接力处理
     * </pre>
     */
    public java.util.List<String>
        getReqPathList() {
      return reqPath_;
    }
    /**
     * <code>repeated string req_path = 5;</code>
     *
     * <pre>
     *	optional string req_src_id = 5;  //req消息的初始发送者，仅用于req/rsp消息的接力处理
     * </pre>
     */
    public int getReqPathCount() {
      return reqPath_.size();
    }
    /**
     * <code>repeated string req_path = 5;</code>
     *
     * <pre>
     *	optional string req_src_id = 5;  //req消息的初始发送者，仅用于req/rsp消息的接力处理
     * </pre>
     */
    public String getReqPath(int index) {
      return reqPath_.get(index);
    }
    /**
     * <code>repeated string req_path = 5;</code>
     *
     * <pre>
     *	optional string req_src_id = 5;  //req消息的初始发送者，仅用于req/rsp消息的接力处理
     * </pre>
     */
    public com.google.protobuf.ByteString
        getReqPathBytes(int index) {
      return reqPath_.getByteString(index);
    }

    private void initFields() {
      msgId_ = "";
      sessionId_ = "";
      seqId_ = 0;
      userData_ = "";
      reqPath_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, seqId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getUserDataBytes());
      }
      for (int i = 0; i < reqPath_.size(); i++) {
        output.writeBytes(5, reqPath_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, seqId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getUserDataBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < reqPath_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(reqPath_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getReqPathList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static TMsgHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TMsgHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TMsgHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TMsgHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TMsgHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TMsgHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static TMsgHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static TMsgHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static TMsgHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TMsgHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(TMsgHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mt.TMsgHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements TMsgHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessagePB.internal_static_mt_TMsgHeader_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessagePB.internal_static_mt_TMsgHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TMsgHeader.class, Builder.class);
      }

      // Construct using com.kedacom.mt.netmanage.protobuf.MessagePB.TMsgHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        seqId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        userData_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        reqPath_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessagePB.internal_static_mt_TMsgHeader_descriptor;
      }

      public TMsgHeader getDefaultInstanceForType() {
        return TMsgHeader.getDefaultInstance();
      }

      public TMsgHeader build() {
        TMsgHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TMsgHeader buildPartial() {
        TMsgHeader result = new TMsgHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.seqId_ = seqId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.userData_ = userData_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          reqPath_ = new com.google.protobuf.UnmodifiableLazyStringList(
              reqPath_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.reqPath_ = reqPath_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TMsgHeader) {
          return mergeFrom((TMsgHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TMsgHeader other) {
        if (other == TMsgHeader.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          bitField0_ |= 0x00000001;
          msgId_ = other.msgId_;
          onChanged();
        }
        if (other.hasSessionId()) {
          bitField0_ |= 0x00000002;
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (other.hasSeqId()) {
          setSeqId(other.getSeqId());
        }
        if (other.hasUserData()) {
          bitField0_ |= 0x00000008;
          userData_ = other.userData_;
          onChanged();
        }
        if (!other.reqPath_.isEmpty()) {
          if (reqPath_.isEmpty()) {
            reqPath_ = other.reqPath_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureReqPathIsMutable();
            reqPath_.addAll(other.reqPath_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TMsgHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TMsgHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string msg_id = 1;
      private Object msgId_ = "";
      /**
       * <code>optional string msg_id = 1;</code>
       *
       * <pre>
       *消息id，唯一标识一个消息
       * </pre>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string msg_id = 1;</code>
       *
       * <pre>
       *消息id，唯一标识一个消息
       * </pre>
       */
      public String getMsgId() {
        Object ref = msgId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string msg_id = 1;</code>
       *
       * <pre>
       *消息id，唯一标识一个消息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg_id = 1;</code>
       *
       * <pre>
       *消息id，唯一标识一个消息
       * </pre>
       */
      public Builder setMsgId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg_id = 1;</code>
       *
       * <pre>
       *消息id，唯一标识一个消息
       * </pre>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg_id = 1;</code>
       *
       * <pre>
       *消息id，唯一标识一个消息
       * </pre>
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }

      // optional string session_id = 2;
      private Object sessionId_ = "";
      /**
       * <code>optional string session_id = 2;</code>
       *
       * <pre>
       *会话id，唯一标识一个会话源
       * </pre>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string session_id = 2;</code>
       *
       * <pre>
       *会话id，唯一标识一个会话源
       * </pre>
       */
      public String getSessionId() {
        Object ref = sessionId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string session_id = 2;</code>
       *
       * <pre>
       *会话id，唯一标识一个会话源
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string session_id = 2;</code>
       *
       * <pre>
       *会话id，唯一标识一个会话源
       * </pre>
       */
      public Builder setSessionId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string session_id = 2;</code>
       *
       * <pre>
       *会话id，唯一标识一个会话源
       * </pre>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string session_id = 2;</code>
       *
       * <pre>
       *会话id，唯一标识一个会话源
       * </pre>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sessionId_ = value;
        onChanged();
        return this;
      }

      // optional uint32 seq_id = 3;
      private int seqId_ ;
      /**
       * <code>optional uint32 seq_id = 3;</code>
       *
       * <pre>
       *序列号，唯一标识一次请求
       * </pre>
       */
      public boolean hasSeqId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 seq_id = 3;</code>
       *
       * <pre>
       *序列号，唯一标识一次请求
       * </pre>
       */
      public int getSeqId() {
        return seqId_;
      }
      /**
       * <code>optional uint32 seq_id = 3;</code>
       *
       * <pre>
       *序列号，唯一标识一次请求
       * </pre>
       */
      public Builder setSeqId(int value) {
        bitField0_ |= 0x00000004;
        seqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 seq_id = 3;</code>
       *
       * <pre>
       *序列号，唯一标识一次请求
       * </pre>
       */
      public Builder clearSeqId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        seqId_ = 0;
        onChanged();
        return this;
      }

      // optional string user_data = 4;
      private Object userData_ = "";
      /**
       * <code>optional string user_data = 4;</code>
       *
       * <pre>
       *特定场景使用，如fcgi请求可以使用该字段存放会话标识，用于返回响应
       * </pre>
       */
      public boolean hasUserData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string user_data = 4;</code>
       *
       * <pre>
       *特定场景使用，如fcgi请求可以使用该字段存放会话标识，用于返回响应
       * </pre>
       */
      public String getUserData() {
        Object ref = userData_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userData_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string user_data = 4;</code>
       *
       * <pre>
       *特定场景使用，如fcgi请求可以使用该字段存放会话标识，用于返回响应
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserDataBytes() {
        Object ref = userData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string user_data = 4;</code>
       *
       * <pre>
       *特定场景使用，如fcgi请求可以使用该字段存放会话标识，用于返回响应
       * </pre>
       */
      public Builder setUserData(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        userData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_data = 4;</code>
       *
       * <pre>
       *特定场景使用，如fcgi请求可以使用该字段存放会话标识，用于返回响应
       * </pre>
       */
      public Builder clearUserData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        userData_ = getDefaultInstance().getUserData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_data = 4;</code>
       *
       * <pre>
       *特定场景使用，如fcgi请求可以使用该字段存放会话标识，用于返回响应
       * </pre>
       */
      public Builder setUserDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        userData_ = value;
        onChanged();
        return this;
      }

      // repeated string req_path = 5;
      private com.google.protobuf.LazyStringList reqPath_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureReqPathIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          reqPath_ = new com.google.protobuf.LazyStringArrayList(reqPath_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string req_path = 5;</code>
       *
       * <pre>
       *	optional string req_src_id = 5;  //req消息的初始发送者，仅用于req/rsp消息的接力处理
       * </pre>
       */
      public java.util.List<String>
          getReqPathList() {
        return java.util.Collections.unmodifiableList(reqPath_);
      }
      /**
       * <code>repeated string req_path = 5;</code>
       *
       * <pre>
       *	optional string req_src_id = 5;  //req消息的初始发送者，仅用于req/rsp消息的接力处理
       * </pre>
       */
      public int getReqPathCount() {
        return reqPath_.size();
      }
      /**
       * <code>repeated string req_path = 5;</code>
       *
       * <pre>
       *	optional string req_src_id = 5;  //req消息的初始发送者，仅用于req/rsp消息的接力处理
       * </pre>
       */
      public String getReqPath(int index) {
        return reqPath_.get(index);
      }
      /**
       * <code>repeated string req_path = 5;</code>
       *
       * <pre>
       *	optional string req_src_id = 5;  //req消息的初始发送者，仅用于req/rsp消息的接力处理
       * </pre>
       */
      public com.google.protobuf.ByteString
          getReqPathBytes(int index) {
        return reqPath_.getByteString(index);
      }
      /**
       * <code>repeated string req_path = 5;</code>
       *
       * <pre>
       *	optional string req_src_id = 5;  //req消息的初始发送者，仅用于req/rsp消息的接力处理
       * </pre>
       */
      public Builder setReqPath(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReqPathIsMutable();
        reqPath_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string req_path = 5;</code>
       *
       * <pre>
       *	optional string req_src_id = 5;  //req消息的初始发送者，仅用于req/rsp消息的接力处理
       * </pre>
       */
      public Builder addReqPath(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReqPathIsMutable();
        reqPath_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string req_path = 5;</code>
       *
       * <pre>
       *	optional string req_src_id = 5;  //req消息的初始发送者，仅用于req/rsp消息的接力处理
       * </pre>
       */
      public Builder addAllReqPath(
          Iterable<String> values) {
        ensureReqPathIsMutable();
        super.addAll(values, reqPath_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string req_path = 5;</code>
       *
       * <pre>
       *	optional string req_src_id = 5;  //req消息的初始发送者，仅用于req/rsp消息的接力处理
       * </pre>
       */
      public Builder clearReqPath() {
        reqPath_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string req_path = 5;</code>
       *
       * <pre>
       *	optional string req_src_id = 5;  //req消息的初始发送者，仅用于req/rsp消息的接力处理
       * </pre>
       */
      public Builder addReqPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReqPathIsMutable();
        reqPath_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mt.TMsgHeader)
    }

    static {
      defaultInstance = new TMsgHeader(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mt.TMsgHeader)
  }

  public interface TMsgBodyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string name = 1;
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     *消息体名称
     * </pre>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     *消息体名称
     * </pre>
     */
    String getName();
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     *消息体名称
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional bytes content = 2;
    /**
     * <code>optional bytes content = 2;</code>
     *
     * <pre>
     *消息体数据
     * </pre>
     */
    boolean hasContent();
    /**
     * <code>optional bytes content = 2;</code>
     *
     * <pre>
     *消息体数据
     * </pre>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code mt.TMsgBody}
   */
  public static final class TMsgBody extends
      com.google.protobuf.GeneratedMessage
      implements TMsgBodyOrBuilder {
    // Use TMsgBody.newBuilder() to construct.
    private TMsgBody(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TMsgBody(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TMsgBody defaultInstance;
    public static TMsgBody getDefaultInstance() {
      return defaultInstance;
    }

    public TMsgBody getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TMsgBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessagePB.internal_static_mt_TMsgBody_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessagePB.internal_static_mt_TMsgBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TMsgBody.class, Builder.class);
    }

    public static com.google.protobuf.Parser<TMsgBody> PARSER =
        new com.google.protobuf.AbstractParser<TMsgBody>() {
      public TMsgBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TMsgBody(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<TMsgBody> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private Object name_;
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     *消息体名称
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     *消息体名称
     * </pre>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     *消息体名称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes content = 2;
    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>optional bytes content = 2;</code>
     *
     * <pre>
     *消息体数据
     * </pre>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes content = 2;</code>
     *
     * <pre>
     *消息体数据
     * </pre>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private void initFields() {
      name_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, content_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, content_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static TMsgBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TMsgBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TMsgBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TMsgBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TMsgBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TMsgBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static TMsgBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static TMsgBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static TMsgBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TMsgBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(TMsgBody prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mt.TMsgBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements TMsgBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessagePB.internal_static_mt_TMsgBody_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessagePB.internal_static_mt_TMsgBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TMsgBody.class, Builder.class);
      }

      // Construct using com.kedacom.mt.netmanage.protobuf.MessagePB.TMsgBody.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessagePB.internal_static_mt_TMsgBody_descriptor;
      }

      public TMsgBody getDefaultInstanceForType() {
        return TMsgBody.getDefaultInstance();
      }

      public TMsgBody build() {
        TMsgBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TMsgBody buildPartial() {
        TMsgBody result = new TMsgBody(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TMsgBody) {
          return mergeFrom((TMsgBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TMsgBody other) {
        if (other == TMsgBody.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TMsgBody parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TMsgBody) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string name = 1;
      private Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       *消息体名称
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       *消息体名称
       * </pre>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       *消息体名称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       *消息体名称
       * </pre>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       *消息体名称
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       *消息体名称
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // optional bytes content = 2;
      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes content = 2;</code>
       *
       * <pre>
       *消息体数据
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes content = 2;</code>
       *
       * <pre>
       *消息体数据
       * </pre>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>optional bytes content = 2;</code>
       *
       * <pre>
       *消息体数据
       * </pre>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes content = 2;</code>
       *
       * <pre>
       *消息体数据
       * </pre>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mt.TMsgBody)
    }

    static {
      defaultInstance = new TMsgBody(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mt.TMsgBody)
  }

  public interface TMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .mt.TMsgHeader header = 1;
    /**
     * <code>optional .mt.TMsgHeader header = 1;</code>
     *
     * <pre>
     *消息头部
     * </pre>
     */
    boolean hasHeader();
    /**
     * <code>optional .mt.TMsgHeader header = 1;</code>
     *
     * <pre>
     *消息头部
     * </pre>
     */
    TMsgHeader getHeader();
    /**
     * <code>optional .mt.TMsgHeader header = 1;</code>
     *
     * <pre>
     *消息头部
     * </pre>
     */
    TMsgHeaderOrBuilder getHeaderOrBuilder();

    // repeated .mt.TMsgBody body = 2;
    /**
     * <code>repeated .mt.TMsgBody body = 2;</code>
     *
     * <pre>
     *消息体
     * </pre>
     */
    java.util.List<TMsgBody>
        getBodyList();
    /**
     * <code>repeated .mt.TMsgBody body = 2;</code>
     *
     * <pre>
     *消息体
     * </pre>
     */
    TMsgBody getBody(int index);
    /**
     * <code>repeated .mt.TMsgBody body = 2;</code>
     *
     * <pre>
     *消息体
     * </pre>
     */
    int getBodyCount();
    /**
     * <code>repeated .mt.TMsgBody body = 2;</code>
     *
     * <pre>
     *消息体
     * </pre>
     */
    java.util.List<? extends TMsgBodyOrBuilder>
        getBodyOrBuilderList();
    /**
     * <code>repeated .mt.TMsgBody body = 2;</code>
     *
     * <pre>
     *消息体
     * </pre>
     */
    TMsgBodyOrBuilder getBodyOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code mt.TMessage}
   */
  public static final class TMessage extends
      com.google.protobuf.GeneratedMessage
      implements TMessageOrBuilder {
    // Use TMessage.newBuilder() to construct.
    private TMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TMessage defaultInstance;
    public static TMessage getDefaultInstance() {
      return defaultInstance;
    }

    public TMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              TMsgHeader.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(TMsgHeader.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                body_ = new java.util.ArrayList<TMsgBody>();
                mutable_bitField0_ |= 0x00000002;
              }
              body_.add(input.readMessage(TMsgBody.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          body_ = java.util.Collections.unmodifiableList(body_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessagePB.internal_static_mt_TMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessagePB.internal_static_mt_TMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TMessage.class, Builder.class);
    }

    public static com.google.protobuf.Parser<TMessage> PARSER =
        new com.google.protobuf.AbstractParser<TMessage>() {
      public TMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TMessage(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<TMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .mt.TMsgHeader header = 1;
    public static final int HEADER_FIELD_NUMBER = 1;
    private TMsgHeader header_;
    /**
     * <code>optional .mt.TMsgHeader header = 1;</code>
     *
     * <pre>
     *消息头部
     * </pre>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .mt.TMsgHeader header = 1;</code>
     *
     * <pre>
     *消息头部
     * </pre>
     */
    public TMsgHeader getHeader() {
      return header_;
    }
    /**
     * <code>optional .mt.TMsgHeader header = 1;</code>
     *
     * <pre>
     *消息头部
     * </pre>
     */
    public TMsgHeaderOrBuilder getHeaderOrBuilder() {
      return header_;
    }

    // repeated .mt.TMsgBody body = 2;
    public static final int BODY_FIELD_NUMBER = 2;
    private java.util.List<TMsgBody> body_;
    /**
     * <code>repeated .mt.TMsgBody body = 2;</code>
     *
     * <pre>
     *消息体
     * </pre>
     */
    public java.util.List<TMsgBody> getBodyList() {
      return body_;
    }
    /**
     * <code>repeated .mt.TMsgBody body = 2;</code>
     *
     * <pre>
     *消息体
     * </pre>
     */
    public java.util.List<? extends TMsgBodyOrBuilder>
        getBodyOrBuilderList() {
      return body_;
    }
    /**
     * <code>repeated .mt.TMsgBody body = 2;</code>
     *
     * <pre>
     *消息体
     * </pre>
     */
    public int getBodyCount() {
      return body_.size();
    }
    /**
     * <code>repeated .mt.TMsgBody body = 2;</code>
     *
     * <pre>
     *消息体
     * </pre>
     */
    public TMsgBody getBody(int index) {
      return body_.get(index);
    }
    /**
     * <code>repeated .mt.TMsgBody body = 2;</code>
     *
     * <pre>
     *消息体
     * </pre>
     */
    public TMsgBodyOrBuilder getBodyOrBuilder(
        int index) {
      return body_.get(index);
    }

    private void initFields() {
      header_ = TMsgHeader.getDefaultInstance();
      body_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, header_);
      }
      for (int i = 0; i < body_.size(); i++) {
        output.writeMessage(2, body_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, header_);
      }
      for (int i = 0; i < body_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, body_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static TMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static TMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static TMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static TMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(TMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mt.TMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements TMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessagePB.internal_static_mt_TMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessagePB.internal_static_mt_TMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TMessage.class, Builder.class);
      }

      // Construct using com.kedacom.mt.netmanage.protobuf.MessagePB.TMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
          getBodyFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = TMsgHeader.getDefaultInstance();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (bodyBuilder_ == null) {
          body_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          bodyBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessagePB.internal_static_mt_TMessage_descriptor;
      }

      public TMessage getDefaultInstanceForType() {
        return TMessage.getDefaultInstance();
      }

      public TMessage build() {
        TMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TMessage buildPartial() {
        TMessage result = new TMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (bodyBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            body_ = java.util.Collections.unmodifiableList(body_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.body_ = body_;
        } else {
          result.body_ = bodyBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TMessage) {
          return mergeFrom((TMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TMessage other) {
        if (other == TMessage.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (bodyBuilder_ == null) {
          if (!other.body_.isEmpty()) {
            if (body_.isEmpty()) {
              body_ = other.body_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureBodyIsMutable();
              body_.addAll(other.body_);
            }
            onChanged();
          }
        } else {
          if (!other.body_.isEmpty()) {
            if (bodyBuilder_.isEmpty()) {
              bodyBuilder_.dispose();
              bodyBuilder_ = null;
              body_ = other.body_;
              bitField0_ = (bitField0_ & ~0x00000002);
              bodyBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBodyFieldBuilder() : null;
            } else {
              bodyBuilder_.addAllMessages(other.body_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .mt.TMsgHeader header = 1;
      private TMsgHeader header_ = TMsgHeader.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          TMsgHeader, TMsgHeader.Builder, TMsgHeaderOrBuilder> headerBuilder_;
      /**
       * <code>optional .mt.TMsgHeader header = 1;</code>
       *
       * <pre>
       *消息头部
       * </pre>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .mt.TMsgHeader header = 1;</code>
       *
       * <pre>
       *消息头部
       * </pre>
       */
      public TMsgHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .mt.TMsgHeader header = 1;</code>
       *
       * <pre>
       *消息头部
       * </pre>
       */
      public Builder setHeader(TMsgHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .mt.TMsgHeader header = 1;</code>
       *
       * <pre>
       *消息头部
       * </pre>
       */
      public Builder setHeader(
          TMsgHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .mt.TMsgHeader header = 1;</code>
       *
       * <pre>
       *消息头部
       * </pre>
       */
      public Builder mergeHeader(TMsgHeader value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != TMsgHeader.getDefaultInstance()) {
            header_ =
              TMsgHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .mt.TMsgHeader header = 1;</code>
       *
       * <pre>
       *消息头部
       * </pre>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = TMsgHeader.getDefaultInstance();
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .mt.TMsgHeader header = 1;</code>
       *
       * <pre>
       *消息头部
       * </pre>
       */
      public TMsgHeader.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .mt.TMsgHeader header = 1;</code>
       *
       * <pre>
       *消息头部
       * </pre>
       */
      public TMsgHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_;
        }
      }
      /**
       * <code>optional .mt.TMsgHeader header = 1;</code>
       *
       * <pre>
       *消息头部
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          TMsgHeader, TMsgHeader.Builder, TMsgHeaderOrBuilder>
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              TMsgHeader, TMsgHeader.Builder, TMsgHeaderOrBuilder>(
                  header_,
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      // repeated .mt.TMsgBody body = 2;
      private java.util.List<TMsgBody> body_ =
        java.util.Collections.emptyList();
      private void ensureBodyIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          body_ = new java.util.ArrayList<TMsgBody>(body_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          TMsgBody, TMsgBody.Builder, TMsgBodyOrBuilder> bodyBuilder_;

      /**
       * <code>repeated .mt.TMsgBody body = 2;</code>
       *
       * <pre>
       *消息体
       * </pre>
       */
      public java.util.List<TMsgBody> getBodyList() {
        if (bodyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(body_);
        } else {
          return bodyBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .mt.TMsgBody body = 2;</code>
       *
       * <pre>
       *消息体
       * </pre>
       */
      public int getBodyCount() {
        if (bodyBuilder_ == null) {
          return body_.size();
        } else {
          return bodyBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .mt.TMsgBody body = 2;</code>
       *
       * <pre>
       *消息体
       * </pre>
       */
      public TMsgBody getBody(int index) {
        if (bodyBuilder_ == null) {
          return body_.get(index);
        } else {
          return bodyBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .mt.TMsgBody body = 2;</code>
       *
       * <pre>
       *消息体
       * </pre>
       */
      public Builder setBody(
          int index, TMsgBody value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBodyIsMutable();
          body_.set(index, value);
          onChanged();
        } else {
          bodyBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mt.TMsgBody body = 2;</code>
       *
       * <pre>
       *消息体
       * </pre>
       */
      public Builder setBody(
          int index, TMsgBody.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          body_.set(index, builderForValue.build());
          onChanged();
        } else {
          bodyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mt.TMsgBody body = 2;</code>
       *
       * <pre>
       *消息体
       * </pre>
       */
      public Builder addBody(TMsgBody value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBodyIsMutable();
          body_.add(value);
          onChanged();
        } else {
          bodyBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .mt.TMsgBody body = 2;</code>
       *
       * <pre>
       *消息体
       * </pre>
       */
      public Builder addBody(
          int index, TMsgBody value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBodyIsMutable();
          body_.add(index, value);
          onChanged();
        } else {
          bodyBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mt.TMsgBody body = 2;</code>
       *
       * <pre>
       *消息体
       * </pre>
       */
      public Builder addBody(
          TMsgBody.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          body_.add(builderForValue.build());
          onChanged();
        } else {
          bodyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mt.TMsgBody body = 2;</code>
       *
       * <pre>
       *消息体
       * </pre>
       */
      public Builder addBody(
          int index, TMsgBody.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          body_.add(index, builderForValue.build());
          onChanged();
        } else {
          bodyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mt.TMsgBody body = 2;</code>
       *
       * <pre>
       *消息体
       * </pre>
       */
      public Builder addAllBody(
          Iterable<? extends TMsgBody> values) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          super.addAll(values, body_);
          onChanged();
        } else {
          bodyBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .mt.TMsgBody body = 2;</code>
       *
       * <pre>
       *消息体
       * </pre>
       */
      public Builder clearBody() {
        if (bodyBuilder_ == null) {
          body_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          bodyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .mt.TMsgBody body = 2;</code>
       *
       * <pre>
       *消息体
       * </pre>
       */
      public Builder removeBody(int index) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          body_.remove(index);
          onChanged();
        } else {
          bodyBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .mt.TMsgBody body = 2;</code>
       *
       * <pre>
       *消息体
       * </pre>
       */
      public TMsgBody.Builder getBodyBuilder(
          int index) {
        return getBodyFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .mt.TMsgBody body = 2;</code>
       *
       * <pre>
       *消息体
       * </pre>
       */
      public TMsgBodyOrBuilder getBodyOrBuilder(
          int index) {
        if (bodyBuilder_ == null) {
          return body_.get(index);  } else {
          return bodyBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .mt.TMsgBody body = 2;</code>
       *
       * <pre>
       *消息体
       * </pre>
       */
      public java.util.List<? extends TMsgBodyOrBuilder>
           getBodyOrBuilderList() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(body_);
        }
      }
      /**
       * <code>repeated .mt.TMsgBody body = 2;</code>
       *
       * <pre>
       *消息体
       * </pre>
       */
      public TMsgBody.Builder addBodyBuilder() {
        return getBodyFieldBuilder().addBuilder(
            TMsgBody.getDefaultInstance());
      }
      /**
       * <code>repeated .mt.TMsgBody body = 2;</code>
       *
       * <pre>
       *消息体
       * </pre>
       */
      public TMsgBody.Builder addBodyBuilder(
          int index) {
        return getBodyFieldBuilder().addBuilder(
            index, TMsgBody.getDefaultInstance());
      }
      /**
       * <code>repeated .mt.TMsgBody body = 2;</code>
       *
       * <pre>
       *消息体
       * </pre>
       */
      public java.util.List<TMsgBody.Builder>
           getBodyBuilderList() {
        return getBodyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          TMsgBody, TMsgBody.Builder, TMsgBodyOrBuilder>
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              TMsgBody, TMsgBody.Builder, TMsgBodyOrBuilder>(
                  body_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:mt.TMessage)
    }

    static {
      defaultInstance = new TMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mt.TMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mt_TMsgHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mt_TMsgHeader_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mt_TMsgBody_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mt_TMsgBody_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mt_TMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mt_TMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rmessage.proto\022\002mt\"e\n\nTMsgHeader\022\016\n\006msg" +
      "_id\030\001 \001(\t\022\022\n\nsession_id\030\002 \001(\t\022\016\n\006seq_id\030" +
      "\003 \001(\r\022\021\n\tuser_data\030\004 \001(\t\022\020\n\010req_path\030\005 \003" +
      "(\t\")\n\010TMsgBody\022\014\n\004name\030\001 \001(\t\022\017\n\007content\030" +
      "\002 \001(\014\"F\n\010TMessage\022\036\n\006header\030\001 \001(\0132\016.mt.T" +
      "MsgHeader\022\032\n\004body\030\002 \003(\0132\014.mt.TMsgBodyB.\n" +
      "!com.kedacom.mt.netmanage.protobufB\tMess" +
      "agePB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_mt_TMsgHeader_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_mt_TMsgHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mt_TMsgHeader_descriptor,
              new String[] { "MsgId", "SessionId", "SeqId", "UserData", "ReqPath", });
          internal_static_mt_TMsgBody_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_mt_TMsgBody_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mt_TMsgBody_descriptor,
              new String[] { "Name", "Content", });
          internal_static_mt_TMessage_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_mt_TMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mt_TMessage_descriptor,
              new String[] { "Header", "Body", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
