@startuml

title __STARTUP's Class Diagram__\n

  namespace com.kedacom.vconf.sdk.main {
    namespace startup {
      enum Msg {
        END
        LoginAps
        LoginApsRsp
        SetMtWorkspace
        SetNetWorkCfg
        StartMtBase
        StartMtSdk
        StartMtSdkRsp
        StartMtService
        StartMtServiceRsp
        ToggleMtFileLog
      }
    }
  }
  

  namespace com.kedacom.vconf.sdk.main {
    namespace startup {
      class com.kedacom.vconf.sdk.main.startup.Msg.MethodOwner {
          {static} - CommonCtrl : String
          {static} - ConfigCtrl : String
          {static} - KernalCtrl : String
          {static} - LoginCtrl : String
          {static} - MonitorCtrl : String
          {static} - MtServiceCfgCtrl : String
          {static} - MtcLib : String
          {static} - PKG : String
      }
    }
  }
  

  namespace com.kedacom.vconf.sdk.main {
    namespace startup {
      class com.kedacom.vconf.sdk.main.startup.StartupManager {
          - bMtSdkStarted : boolean
          - context : Context
          {static} - instance : StartupManager
          {static} - modelMap : Map<EmMtModel, String>
          - startingSrvList : List<String>
          {static} + getInstance()
          + start()
          + start()
          # ntfsProcessors()
          # rspsProcessors()
          - StartupManager()
          - convertTransType()
          - onRsps()
          - startServices()
      }
    }
  }
  

  namespace com.kedacom.vconf.sdk.main {
    namespace startup {
      class com.kedacom.vconf.sdk.main.startup.ToDoConverter {
          {static} ~ fromTransferObj()
          {static} ~ toTransferObj()
      }
    }
  }
  

  com.kedacom.vconf.sdk.main.startup.Msg +-down- com.kedacom.vconf.sdk.main.startup.Msg.MethodOwner
  com.kedacom.vconf.sdk.main.startup.StartupManager -up-|> com.kedacom.vconf.sdk.amulet.Caster


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
