


@startuml

title <size:24><b>数据协作基本流程\n\n

start

:登录数据协作;


:加入/创建数据协作;

if (自由协作模式or管理员控制模式？) then (管理员控制模式)

    :申请协作权;

    if (成功？) then (是)
        :接收/发送数据协作;
    else (否)
        :接收数据协作;
    endif

else (自由协作模式)
    :接收/发送数据协作;
endif

    :退出/结束数据协作;

    :注销数据协作;
    stop

@enduml
